spring:
  thymeleaf:
    mode: Html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/merlinsblog?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 9911
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

logging:
  level:
    root: info
    com.merlin.merlinsblog: debug
  file:
    path: .\log\
#  pattern:
##    console: {yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n
#    file: clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow}
#    com.merlin.merlinsblog: trace
